spring.application.name=recru
spring.datasource.url=jdbc:postgresql://localhost:5432/recru
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Secret utilisé pour signer le JWT (à ne pas hardcoder en production)
jwt.secret=MTEyOTA4NjU4ODAzOTQ3OTI5ODlzZWNyZXRrZXlmb3IyNTZiaXRzMTIzNDU2Nzg5MDEyMzQ=

# Durée d'expiration du token en millisecondes (ici 1 heure)
jwt.expiration=3600000


